### ISSUE TITLE
Rework README

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-example#3]
GFM does not support table widths, so we are left with squished columns for the example names. I am proposing we lists instead:

---

## Getting started examples

1. [loopback-getting-started]()
  - The basics on ...
2. [loopback-getting-started-intermediate]()
  - Lorem ipsum dolor...

## Topic-specific examples

- [loopback-example-angular]()
  - Lorem ipsum dolor...
- [loopback-example-app]()
  - Lorem ipsum dolor...
  - Lorem ipsum dolor...

---

A side benefit of using lists is we can have multiple descriptions for each example..

**Comment by superkhau** [comment]
@crandmck Thoughts and do you want to take this one?

**Comment by crandmck** [comment]
You can force column widths as I did using the `&nbsp;` HTML entity.  Yes, it's an ugly hack, but the ugliness is only apparent when editing the markdown, not when viewing it.  I did this to the table, but you seem to have removed it for some reason.  For example, see https://github.com/strongloop/loopback-example/blob/9407da1028540257ea56271411f29bdcc3de2cc2/README.md.

I don't like bullet lists for things like this.  They are harder to read and scan.  I would strongly prefer to keep the tables and format them as I did so they layout nicely.  Bullet lists are fine for listing smallish numbers of things in a sentence, but not for something like this.

**Comment by superkhau** [comment]
I just cleaned up everything so we have a fresh slate to work on. I will try it out with your `&nbsp;` hack to see if we can make it look good with tables. If it works, that would be the best case.

**Comment by crandmck** [comment]
I updated my comment above re using HTML instead.  Think about that and we can chat.

**Comment by superkhau** [comment]
I don't mind using HTML if it actually works. I haven't tested `width` but I know `style` attributes don't work on GH. Let's give that a shot first before resorting to the `nbsp;` hack.

**Comment by crandmck** [comment]
Rand to do the following:
1. Fix column widths
2. Add back sections with separate tables.
3. Redo Overview section
4. Update TOC

**Comment by superkhau** [comment]
One more thing: @altsang gave me access to the `strongloop-archive` org, so we can put the deprecated private repos there. You will need @altsang to add you to the org too.

**Comment by crandmck** [comment]
Updated README per above.  There wasn't much in the Overview, so I just replaced with a sentence at the top.

**Comment by superkhau** [comment]
>... (see loopback-example-database for example using database connectors).

"for example using database connectors)" needs fixing.

>These examples illustrate using LoopBack's client SDKs.

"illustrate using" needs fixing.

**Comment by superkhau** [comment]
Also, we should organize the examples in each section alphabetically. ie) connector section and client sdk section

**Comment by superkhau** [comment]
LGTM

**Comment by crandmck** [comment]
Addressed the issues you mentioned in Slack.
